### ISSUE TITLE
Mod Manager never passes load screen.

### ISSUE THREAD

**Issue by Shadowblade7x** [MatuxGG/ModManager#26]
Opening normally letting it sit for 5 minutes, as administrator and letting it sit for 5 minutes, restarting, installing .net, reinstalling .net, allowing bypass through Windows Firewall, disabling Windows Firewall, restarting again, reinstalling everything again, using the zip, unblocking before unzipping, starting normally or administrator - all of these were tested and my mod manager will not pass this stage. Since we're FORCED to update to use the new launcher, I - and anyone else who is experiencing this - can no longer use the mod manager until this is fixed.
![amoogus](https://user-images.githubusercontent.com/37427291/117518209-1b038680-af5c-11eb-9aa4-3e7e8cc518bf.png)

**Comment by MatuxGG** [comment]
Please uninstall both Mod Manager and Among Us. Then, make the install of both. It will solve your issue.

This is explained in the FAQ available on discord and matux.fr.
It's because you previously used Mod Manager 3 that made changes as admin and Mod Manager 4 no longer needs and require admin privileges.

Confirm me that it works then ;)

**Comment by zeldaking** [comment]
I'm having the same problem I did everything you said but it still will not work

**Comment by MatuxGG** [comment]
Please, consider joining the discord server and opening a ticket for more help

**Comment by MatuxGG** [comment]
I have no answer from any of you. I close this ticket. Feel free to reopen it if it's not solved.

**Comment by Shadowblade7x** [comment]
I wasn't getting notifications of updates so I thought none were being posted on this issue. 
I had already tried what you suggested, but I went ahead and ran them through again and it did not fix it. I went to just downloading them manually so I didn't check back until I got the closed notification.

**Comment by MatuxGG** [comment]
Please, do the following then : 
- Uninstall Mod Manager
- Remove the folder "Mod Manager" in appdata (You can press Windows + R and enter "%APPDATA%")
- Reinstall Among Us
- Install Mod Manager again from release 4.0.4

It will work for sure after these steps as this issue is linked to the fact that the previous version of Mod Manager used admin privileges.

I did the choice of not providing many versions of Mod Manager (aka forced updates) because :
- Mod Manager relies on a server with a list of mods
- Mods are depending on a game version to work properly
- I make this on my free time and I'm not even paid for it (I don't need it tho). However, I'm paying for servers each month.

Hopefully, you understand and this will solve your issue ^^

**Comment by MatuxGG** [comment]
If it doesn't make the job for you still, please upload your logs here :
- Press Windows + R
- Enter %APPDATA%/ModManager
- Upload log.txt here

**Comment by Shadowblade7x** [comment]
It is still freezing after the load bar. I can give you a gif representation of what's happening and upload the log file.
[log.txt](https://github.com/MatuxGG/ModManager/files/6488355/log.txt)
and here's the gif https://i.gyazo.com/88eb2acf85d27b014fc632cc7d1de987.mp4

**Comment by MatuxGG** [comment]
You're absolutely right, it's good if someone else have this issue. Let's see if we can find a solution then. 

Apparently, Mod Manager can't find the config file. There are two possible causes for this and either one should be solved by recreating appdata/ModManager folder.

So I have to ask again : did you try removing appdata/ModManager folder as I told you ? Not the content bu the folder itself.

**Comment by Shadowblade7x** [comment]
I did delete the folder, and did reinstall Among Us. I do use it via Steam. Sorry for the delay in messaging, I still don't get email updates when these go through ;/
Does it have anything to do with Among Us being on a different harddrive perhaps?

**Comment by MatuxGG** [comment]
There is no problem with using a different hard disk. I use one myself and it works.

Maybe try to download visual c++ redistributable 2015. Here is the link : https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Shadowblade7x** [comment]
Sorry for the delay, work's been super busy. I tried to download this knowing I had a higher version just to see what'd happen and it just ended up saying the installation failed because I had a higher version. 

As much as it doesn't help, mine has started working again suddenly. With no change to anything besides a failed update to the redist (because of the higher version thing). Obviously I've done other stuff as well, but nothing that should have directly impacted this.

Is there anything you'd want to try to see why? Otherwise it at least works again :D

**Comment by MatuxGG** [comment]
Since your last message, a few other people had the same issue. Apparently, the issue is solved automatically after restarting the computer at some time.
As a consequence, I think some files may be not accessible for Mod Manager before a restart, even after following every guidelines in FAQ :(

Can you confirm that you restarted your computer at some point ?

**Comment by Shadowblade7x** [comment]
Yeah, I had to restart it recently due to an update on some things I had to update before I could keep working lol. It must have started working after that.
